### PR TITLE
Arizona - only grab VBM email; refactor

### PR DESCRIPTION
**Pull request by twagner000**

### CODE REVIEW

**Comment by tianhuil** [comment]
I would rather send to more emails than fewer

**Comment by Luca409** [comment]
Hm, alright, sorry Tristan.  Do you want to just remove the part where you parse fewer emails since you still did some refactoring?

**Comment by tianhuil** [comment]
Splitting up the PR makes sense.  We can always decide to select fewer emails if we want.

**Comment by twagner000** [comment]
Ok, I updated the pr to be just the refactor (still pulls ***all*** emails for each county).

**Pull request merged**
